#!/bin/bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Copyright (c) 2023 SUSE LLC
#
# Author: Joerg Roedel <jroedel@suse.de>

RET=0
CHECK_SPDX="$(git rev-parse --show-toplevel)/scripts/check-spdx.sh"

for file in `git diff --diff-filter=d --name-only --staged`; do
    ext=${file##*.}
    if [ "$ext" == "rs" ]; then
        rustfmt --check $file > /dev/null 2>&1
        if [ "$?" == "1" ]; then
            echo "$file needs rustfmt checking"
            RET=1
        fi
    fi
    "$CHECK_SPDX" --file "$file" || RET=1
done

make clippy || exit 1

exit $RET

